services:
  db:
    image: postgres:17
    container_name: postgres-mutmat
    restart: unless-stopped
    shm_size: 128mb 
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-mutmat_user} -d $${DB_NAME:-mutmat}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: mutmat-backend
    build: .
    container_name: backend-mutmat
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - assets:/app/assets
      - media:/app/media

  front:
    image: mutmat-frontend
    build: 
      context: ./fronttheque
      dockerfile: Dockerfile
    container_name: frontend-mutmat
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend


  frontend-proxy:
    image: nginx
    container_name: nginx-mutmat
    restart: unless-stopped
    ports:
      # Expose both HTTP and HTTPS to the outside world
      - "80:8001"
      - "443:443"

      # ONLY expose HTTP to localhost. Hidden from the outside world.
      # - "127.0.0.1:8089:80"
    depends_on:
      - backend
      - front   
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro # Removed the SSL volume mount, if Host NGINX handles this part
      - assets:/app/assets
      - media:/app/media

volumes:
  postgres_data:
  assets:
  media: