services:
  db:
    image: postgres:17
    container_name: postgres-matos
    restart: always
    shm_size: 128mb 
    ports:
      - "5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-postgres} -d $${DB_NAME:-matostheque}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: django-matos-backend
    build: .
    container_name: backend-matos
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - assets:/app/assets
      - media:/app/media 

  frontend:
    image: django-matos-frontend
    build: 
      context: ./fronttheque
      dockerfile: Dockerfile
    container_name: frontend-matos
    restart: always
    env_file:
      - .env
    depends_on:
      - backend

  frontend-proxy:
    image: nginx:latest
    container_name: nginx-matos
    restart: always
    ports:
      - "80:8001" 
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - assets:/app/assets
      - media:/app/media
  
volumes:
  postgres_data:
  assets:
  media: