services:
  db:
    image: postgres:17
    container_name: postgres-mutmat
    restart: unless-stopped
    shm_size: 128mb 
    ports:
      - "5434:5432" # HOST_PORT:CONTAINER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-mutmat_user} -d $${DB_NAME:-mutmat}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dockerNet

  backend:
    image: mutmat-backend
    build: .
    container_name: backend-mutmat
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    # ports:
    #   - "8020:8020"
    volumes:
      - assets:/app/assets
      - media:/app/media
    networks:
      - dockerNet

  front:
    image: mutmat-frontend
    build: 
      context: ./fronttheque
      dockerfile: Dockerfile
    container_name: frontend-mutmat
    restart: unless-stopped
    # ports:
    #   - "3020:3020"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - dockerNet

  frontend-proxy:
    image: nginx:latest
    container_name: nginx-mutmat
    restart: unless-stopped
    ports:
      # Expose both HTTP and HTTPS to the outside world
      - "80:8001"
      - "443:443"
    depends_on:
      - backend
      - front   
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - assets:/app/assets
      - media:/app/media
    networks:
      - dockerNet

volumes:
  postgres_data:
  assets:
  media:

networks:
  dockerNet:
    external: true # Ensure you run `docker network create dockerNet` first