# Generated by Django 4.2.23 on 2026-07-07 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('laboratory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(max_length=100)),
                ('laboratory_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('material_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manual_link', models.CharField(blank=True, max_length=255, null=True)),
                ('datasheet_link', models.CharField(blank=True, max_length=255, null=True)),
                ('qrcode', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('LAB_SUPPLIES', 'Lab Supplies'), ('CONSUMABLES', 'Consumables')], max_length=100)),
                ('sub_type', models.CharField(choices=[('FILTERS_FILTRATION_SUPPLIES', 'Filters and Filtration Supplies'), ('BIOLOGICAL_CONSUMABLES', 'Biological Consumables'), ('CHEMICALS', 'Chemicals'), ('SAFETY_EQUIPMENT', 'Safety Equipment'), ('LAB_FURNITURE_FIXTURES', 'Lab Fixtures'), ('CLEANING_MAINTENANCE_SUPPLIES', 'Cleaning and Maintenance Supplies'), ('COMPUTING', 'Computing'), ('ELECTRONICS', 'Electronics'), ('MECHANICAL', 'Mechanical'), ('OPTICS_LASER', 'Optics or Laser'), ('GAS_FLUIDS', 'Gas or Fluids'), ('BIOLOGICAL', 'Biological'), ('CHEMISTRY', 'Chemistry'), ('BOOKS', 'Books'), ('OFFICE_BUILDING', 'Office and Building'), ('Others', 'Others')], max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('loan_duration', models.IntegerField(blank=True, default=30, null=True)),
                ('quantity_available', models.FloatField(default=1)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('validation', models.BooleanField(default=True)),
                ('available_for_transaction', models.BooleanField(default=True)),
                ('is_Movable', models.BooleanField(default=False)),
                ('is_formation_required', models.BooleanField(default=False)),
                ('code_nacre', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
                'db_table': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], default='user', max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profil_pic', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mutmat.laboratory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mutmat.service')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='TrustCircle',
            fields=[
                ('trust_circle_id', models.AutoField(primary_key=True, serialize=False)),
                ('trust_circle_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ManyToManyField(related_name='trust_circles', to='Mutmat.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Loan', 'Loan'), ('Donation', 'Donation')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('transaction_status', models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Borrowed', 'Borrowed'), ('Overdue', 'Overdue'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('Booked', 'Booked')], default='Pending Validation', max_length=20)),
                ('transaction_quantity', models.FloatField(default=1)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('latest_change_status_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loans', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_loans', to='Mutmat.materials')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('General', 'General'), ('Event', 'Event'), ('Error', 'Error'), ('Overdue Alert', 'Overdue Alert'), ('Request Alert', 'Request Alert')], default='General', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('description', models.TextField()),
                ('title', models.CharField(default='', max_length=100)),
                ('resolved_flag', models.BooleanField(default=False)),
                ('read_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_notifications', to='Mutmat.transactions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='materials',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mutmat.service'),
        ),
        migrations.AddField(
            model_name='materials',
            name='trust_circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trust_circle_materials', to='Mutmat.trustcircle'),
        ),
        migrations.AddField(
            model_name='materials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='services',
            field=models.ManyToManyField(related_name='laboratories', to='Mutmat.service'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comments', to='Mutmat.comments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'db_table': 'Comments',
            },
        ),
    ]
