from datetime import datetime
import qrcode, io, os, json, base64, uuid

from django.conf import settings
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404

from Matostheque.models.material_model import Materials 
from Matostheque.models.loan_model import Loans 
from Matostheque.serializers import LoanSerializer
from Matostheque.serializers import MaterialSerializer

from rest_framework import status

def get_material(pk):
    """
    Function to return a material instance given a primary key.
    """
    return Materials.objects.get(pk=pk)

def generate_qrcode(device_id, device_name, team):
    """
    Function to generate material qrcode.

    Args:
        device_id (int): the equipment id
        device_name (str): (optional) material name in string format
        team (str): (optional) team of the owner in string format

    Returns:
        qr_img_bytes: returns generated bytes representing the blob of the qrcode to be stored.
    """

    # Create a link to a web page with the material details
    webpage_link = f"https://liphy-annuaire.univ-grenoble-alpes.fr/matostheque/public/{device_id}"

    # Generate the qrcode with the link
    # qr = qrcode.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=10, border=14)
    qr = qrcode.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=20, border=14)
    qr.add_data(webpage_link)  
    qr.make(fit=True)
    
    # Converting to an image
    qr_img = qr.make_image(fill_color="black", back_color="white")

    # Save QR code image to a BytesIO object
    qr_img_bytes = io.BytesIO()
    qr_img.save(qr_img_bytes, format='PNG')
    qr_img_bytes.seek(0)

    return qr_img_bytes

def upload_images(files, pk):
    """
    Function to upload images to the server.

    Args:
        files (list of obj) : A list of file object to be uploaded

    Returns:
        uploaded_images (json): returns a json list of the paths where the files were uploaded
    """
    
    uploaded_images = []
    folder_path = os.path.join(settings.MEDIA_ROOT, 'images')
    # Create the folder if it doesn't exist
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
        
    for key, uploaded_file in files.items():
        # Generate a unique identifier for the file
        file_uuid = uuid.uuid4().hex[:6] 
        
        # Generate a unique filename for the image
        filename = f'material{pk}__{file_uuid}.jpg'  # You can adjust the extension as needed
        
        # Construct the full file path
        file_path = os.path.join(folder_path, filename)
        
        # Save the uploaded file as an image to the specified folder
        with open(file_path, 'wb') as destination:
            # Iterate over the file chunks and write them to the destination
            for chunk in uploaded_file.chunks():
                destination.write(chunk)
                
        uploaded_images.append(f'images/{filename}')
    
    response_data = json.dumps(uploaded_images)
    return response_data if len(uploaded_images) > 0 else None

def on_create_material(request):
    """
    Function to create a new instance of material.

    Args:
        request (obj) : An oject with the necessary information to create a new material object

    Returns:
       (json): returns the newly created material instance or an error.
    """
    # Retrieve the data posted before accessing the files (need to access POST before FILES)
    mutable_data = request.POST.copy()
    
    # Serializing the data
    material_serializer = MaterialSerializer(data=mutable_data)
    
    # Validating the serialized data
    if material_serializer.is_valid():
        try:
            created_instance = material_serializer.save() # saving instance
        except Exception as e:
            print(e)
        # Qrcode generation with the created instance, needed in this order to access the new id
        img = generate_qrcode(
            created_instance.material_id,
            created_instance.material_title,
            created_instance.team
        )
        
        # Assigning the qrcode to the instance and saving
        encoded_img =  base64.b64encode(img.getvalue()).decode('utf-8')
        created_instance.qrcode = encoded_img
        created_instance.save()
        
        # Upload attached images 
        images_response = upload_images(request.FILES, created_instance.material_id)
        
        # Assigning the image paths to the instance and saving
        if images_response is not None:
            created_instance.images = images_response
            created_instance.save()

        # Returning the created material data
        return JsonResponse(material_serializer.data, status=status.HTTP_201_CREATED) 
    
    print(material_serializer.errors)
    # Returning an error when the serialized data is not valid
    return JsonResponse(material_serializer.errors, status=status.HTTP_400_BAD_REQUEST) 

def get_detailed_material(pk):
    """
    Function to return a list of detailed information related to a list of materials.

    Args:
        pk (int) : The id of the material instance 

    Returns:
       detailed_materials (obj): A list of information related to the material instance.
    """
    material = get_object_or_404(Materials.objects.select_related('owner__user'), pk=pk)
    detailed_materials = MaterialSerializer(material).data
    owner = material.owner
    user = owner.user
    
    detailed_materials['owner_details'] = {
        "owner_id": owner.owner_id,
        "contact": owner.contact,
        "user_id": user.user_id,
        "first_name": user.first_name,
        "last_name": user.last_name,
        "email": user.email
    }
    
    return detailed_materials

def get_events_detail(pk):
    """
    Function to return a list of loans related to a material.

    Args:
        pk (int) : The id of the material instance 

    Returns:
       events (obj): A list of loan related to the material instance.
    """
    events =  []
    loans =  Loans.objects.filter(material=pk)
    for loan in loans:
        loan_data = LoanSerializer(loan).data
        borrower = loan.borrower
        loan_data['borrower_details'] = {
            'first_name' : borrower.first_name,
            'last_name' : borrower.last_name,
            'email' : borrower.email
        }
        events.append(loan_data)
    return events

def get_events_detail_lite(pk):
    """
    Function to return a lite list of loans related to a material.

    Args:
        pk (int) : The id of the material instance 

    Returns:
       events (obj): A lite list of loan related to the material instance.
    """
    events =  []
    loans =  Loans.objects.filter(material=pk)
    if loans is not None : 
        for loan in loans:
            loan_data = LoanSerializer(loan).data
            events.append({
                'loan_id': loan_data["loan_id"],
                'material': loan_data["material"],
                'loan_date': loan_data["loan_date"], 
                'duration': loan_data["duration"],
                'loan_status': loan_data["loan_status"]
            })
    return events
