from datetime import datetime
import qrcode, io, os, json, base64, uuid

from django.conf import settings
from django.contrib.auth import get_user_model
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404

from Matostheque.models.material_model import Materials 
from Matostheque.models.transaction_model import Transactions
from Matostheque.serializers import TransactionSerializer
from Matostheque.serializers import MaterialSerializer

from rest_framework import status

from dotenv import load_dotenv

from datetime import timedelta
from django.utils import timezone

# Load the .env file from its specific location
env_path = os.path.join(settings.BASE_DIR, '..', '.env') 
load_dotenv(env_path)

def get_material(pk):
    """
    Function to return a material instance given a primary key.
    """
    return Materials.objects.get(pk=pk)

def generate_qrcode(device_id):
    """
    Function to generate material qrcode.

    Args:
        device_id (int): the equipment id

    Returns:
        qr_img_bytes: returns generated bytes representing the blob of the qrcode to be stored.
    """

    # Create a link to a web page with the material details
    webpage_link = f"https://localhost/matostheque/public/{device_id}"

    # Generate the qrcode with the link
    qr = qrcode.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=20, border=14)
    qr.add_data(webpage_link)  
    qr.make(fit=True)
    
    # Converting to an image
    qr_img = qr.make_image(fill_color="black", back_color="white")

    # Save QR code image to a BytesIO object
    qr_img_bytes = io.BytesIO()
    qr_img.save(qr_img_bytes, format='PNG')
    qr_img_bytes.seek(0)

    return qr_img_bytes

def upload_images(files, pk):
    """
    Function to upload images to the server.

    Args:
        files (list of obj) : A list of file object to be uploaded
        pk (int): The id of the material instance

    Returns:
        uploaded_images (json): returns a json list of the paths where the files were uploaded
    """
    
    uploaded_images = []
    folder_path = os.path.join(settings.MEDIA_ROOT, 'images')
    # Create the folder if it doesn't exist
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
        
    for key, uploaded_file in files.items():
        # Generate a unique identifier for the file
        file_uuid = uuid.uuid4().hex[:6] 
        
        # Generate a unique filename for the image
        filename = f'material{pk}__{file_uuid}.jpg'  # You can adjust the extension as needed
        
        # Construct the full file path
        file_path = os.path.join(folder_path, filename)
        
        # Save the uploaded file as an image to the specified folder
        with open(file_path, 'wb') as destination:
            # Iterate over the file chunks and write them to the destination
            for chunk in uploaded_file.chunks():
                destination.write(chunk)
                
        uploaded_images.append(f'images/{filename}')
    
    response_data = json.dumps(uploaded_images)
    return response_data if len(uploaded_images) > 0 else None

def on_create_material(request):
    """
    Function to create a new instance of material.

    Args:
        request (obj) : An oject with the necessary information to create a new material object

    Returns:
       (json): returns the newly created material instance or an error.
    """
    # Retrieve the data posted before accessing the files (need to access POST before FILES)
    mutable_data = request.POST.copy()
    mutable_data["available_for_transaction"] = "true"
    user = get_user_model().objects.get(pk=mutable_data["user"])
    if request.user.laboratory != user.laboratory:
        return JsonResponse({'message': "You can't create a material for this owner"},status=status.HTTP_400_BAD_REQUEST)
    # Serializing the data
    material_serializer = MaterialSerializer(data=mutable_data)

    # Validating the serialized data
    if material_serializer.is_valid():
        try:
            created_instance = material_serializer.save() # saving instance

            # Qrcode generation with the created instance, needed in this order to access the new id
            img = generate_qrcode(created_instance.material_id)

            # Assigning the qrcode to the instance and saving
            encoded_img = base64.b64encode(img.getvalue()).decode('utf-8')
            created_instance.qrcode = encoded_img
            created_instance.save()

            # Upload attached images
            images_response = upload_images(request.FILES, created_instance.material_id)

            # Assigning the image paths to the instance and saving
            if images_response is not None:
                created_instance.images = images_response
                created_instance.save()

            # Returning the created material data
            return JsonResponse(material_serializer.data, status=status.HTTP_201_CREATED)
        except Exception as e:
            raise e
    # Returning an error when the serialized data is not valid
    raise Exception(material_serializer.errors)

def get_detailed_material(pk):
    """
    Function to return a list of detailed information related to a list of materials.

    Args:
        pk (int) : The id of the material instance 

    Returns:
       detailed_materials (obj): A list of information related to the material instance.
    """
    material = get_object_or_404(Materials.objects.select_related('user'), pk=pk)
    detailed_materials = MaterialSerializer(material).data
    user = material.user
    if (material.type == 'LAB_SUPPLIES'):
        detailed_materials["availability"] = is_available(pk=pk)
    else:
        detailed_materials["availability"] = material.available_for_transaction

    detailed_materials['owner_details'] = {
        "user_id": user.user_id,
        "first_name": user.first_name,
        "last_name": user.last_name,
        "phone_number": user.phone_number,
        "email": user.email,
    }

    return detailed_materials

def get_events_detail(pk):
    """
    Function to return a list of transactions related to a material.

    Args:
        pk (int) : The id of the material instance 

    Returns:
       events (obj): A list of transaction related to the material instance.
    """
    events =  []
    transactions =  Transactions.objects.filter(material=pk).filter(transaction_status__in=['Booked','Borrowed','Overdue','Closed'])
    for transaction in transactions:
        transaction_data = TransactionSerializer(transaction).data
        borrower = transaction.borrower
        transaction_data['borrower_details'] = {
            'first_name' : borrower.first_name,
            'last_name' : borrower.last_name,
            'email' : borrower.email
        }
        events.append(transaction_data)
    return events

def get_events_detail_lite(pk):
    """
    Function to return a lite list of transactions related to a material.

    Args:
        pk (int) : The id of the material instance 

    Returns:
       events (obj): A lite list of transaction related to the material instance.
    """
    events =  []
    transactions =  Transactions.objects.filter(material=pk).filter(transaction_status__in=['Booked','Borrowed','Overdue','Closed'])
    if transactions is not None :
        for transaction in transactions:
            transaction_data = TransactionSerializer(transaction).data
            events.append({
                'transaction_date': transaction_data["transaction_date"],
                'duration': transaction_data["duration"],
            })
    return events


def is_available(pk):
    """
    Function to return boolean to know if a material is actually transaction

    Args:
        pk (int) : The id of the material instance

    Returns:
       is_available (boolean): A boolean to know if a material is actually transaction
    """
    material = Materials.objects.get(pk=pk)
    if not material.available_for_transaction:
        return False
    transactions =  Transactions.objects.filter(material=pk).filter(transaction_status__in=['Booked','Borrowed'])
    if transactions is not None :
        nbused = 0
        for transaction in transactions:
            date_fin = transaction.transaction_date + timedelta(days= int(transaction.duration) - 1)
            if transaction.transaction_date <= timezone.now().date() <= date_fin:
                nbused = nbused + transaction.transaction_quantity
    return True