# Generated by Django 5.0.3 on 2024-05-28 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('material_title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_link', models.CharField(blank=True, max_length=255, null=True)),
                ('datasheet_link', models.CharField(blank=True, max_length=255, null=True)),
                ('qrcode', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('LAB_SUPPLIES', 'Lab Supplies'), ('CONSUMABLES', 'Consumables')], max_length=100)),
                ('consumable_type', models.CharField(blank=True, choices=[('FILTERS_FILTRATION_SUPPLIES', 'Filters and Filtration Supplies'), ('BIOLOGICAL_CONSUMABLES', 'Biological Consumables'), ('CHEMICALS', 'Chemicals'), ('SAFETY_EQUIPMENT', 'Safety Equipment'), ('LAB_FURNITURE_FIXTURES', 'Lab Fixtures'), ('CLEANING_MAINTENANCE_SUPPLIES', 'Cleaning and Maintenance Supplies')], max_length=100, null=True)),
                ('quantity_available', models.FloatField(default=0.0, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('loan_duration', models.IntegerField(null=True)),
                ('availability', models.BooleanField(default=True)),
                ('validation', models.BooleanField(default=True)),
                ('available_for_loan', models.BooleanField(default=True)),
                ('code_nacre', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_price', models.FloatField(default=0.0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Materials',
                'db_table': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Owners',
                'db_table': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('location', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('loan_status', models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Borrowed', 'Borrowed'), ('Overdue', 'Overdue'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('Booked', 'Booked')], default='Pending Validation', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('overdue_flag', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_loans', to='Matostheque.materials')),
            ],
            options={
                'verbose_name_plural': 'Loans',
                'db_table': 'Loans',
            },
        ),
        migrations.AddField(
            model_name='materials',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_materials', to='Matostheque.owners'),
        ),
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], default='user', max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profil_pic', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='owners',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('General', 'General'), ('Event', 'Event'), ('Error', 'Error'), ('Overdue Alert', 'Overdue Alert'), ('Request Alert', 'Request Alert')], default='General', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('description', models.TextField()),
                ('title', models.CharField(default='', max_length=100)),
                ('resolved_flag', models.BooleanField(default=False)),
                ('read_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_notifications', to='Matostheque.loans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loans',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
