# Generated by Django 4.2.23 on 2026-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0002_alter_customusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='materials',
            name='loan_duration',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
