# Generated by Django 5.0.3 on 2024-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0003_alter_comments_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('COMPUTING', 'Computing'), ('CHEMISTRY', 'Chemistry')], max_length=100, null=True),
        ),
    ]
