# Generated by Django 5.0.3 on 2024-10-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0004_materials_supply_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='supply_type',
        ),
    ]
