# Generated by Django 5.0.3 on 2024-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0007_remove_materials_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('COMPUTING', 'Computing'), ('CHEMISTRY', 'Chemistry')], max_length=100, null=True),
        ),
    ]
