# Generated by Django 5.0.3 on 2024-10-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0008_materials_quantity_materials_supply_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='supply_type',
        ),
    ]
