# Generated by Django 5.0.3 on 2024-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0011_remove_materials_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='lab_supply_quantity',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='lab_supply_type',
            field=models.CharField(blank=True, choices=[('INFORMATICS', 'Informatics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology')], max_length=100, null=True),
        ),
    ]
