# Generated by Django 5.0.3 on 2024-10-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0012_materials_lab_supply_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='lab_supply_quantity',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='lab_supply_type',
        ),
    ]
