# Generated by Django 5.0.3 on 2024-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0013_remove_materials_lab_supply_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='lab_supply_quantity',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='lab_supply_type',
            field=models.CharField(blank=True, choices=[('COMPUTING', 'Computing'), ('CHEMISTRY', 'Chemistry')], max_length=100, null=True),
        ),
    ]
