# Generated by Django 5.0.3 on 2024-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0014_materials_lab_supply_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='lab_supply_type',
            field=models.CharField(blank=True, choices=[('GENERAL_SUPPLIES', 'General Supplies'), ('BUILDINGS_INFRASTRUCTURE_WORKS_GREEN_SPACES', 'Building, Infrastructure, Works and Green spaces'), ('COMMUNICATION_CULTURE_DOCUMENTATION', 'Communication, Culture and Documentation'), ('TRAVEL_TRANSPORT_ACCOMMODATION', 'Travel : Transport and Accomodation '), ('STUDIES_CONSULTING_INSURANCE_PI_HUMAN_RESOURCES', 'Studies, Consulting, Insurance, Human Resources'), ('FREIGHT_SHIPPING_TRANSPORT_MOVING', 'Freight, Shipping, Transport and Moving'), ('LABORATORY_WORKSHOP_GASES_CRYOGENICS', 'Laboratories or Workshop Gases, Cryogenics '), ('HYGIENE_SAFETY', 'Hygiene and Safety at Work'), ('IT_TELECOMMUNICATIONS_AUDIOVISUAL', 'IT, Telecommunications and Audiovisual'), ('LABORATORY_TP_ROOM_FITTINGS', 'Laboratory and TP Room Fittings'), ('ANIMAL_EXPERIMENTATION_ANIMAL_BREEDING_ANIMAL_CONSERVATION_ANIMAL_STUDIES', 'Animal Experimentation, Animal Breeding, Animal Conservation and Animal Studies'), ('MEDICAL', 'Mecidal'), ('MICROSCOPY_PROFILOMETRY', 'Microscopy and Profilometry'), ('CHEMISTRY_BIOLOGY', 'Chemistry and Biology'), ('OPTO_LASERS_OPTICAL_EQUIPMENT', 'Opto, Lasers and Optical Equipement'), ('PHYSICS_NUCLEAR_CORPUSCULAR_PHYSICS', 'Physics, Nuclear and Corpuscular Physics'), ('PLANT_EXPERIMENTATION', 'Plant Experimentation'), ('WORKSHOP_MECHANICS_AUTOMATION', 'Workshop, Mechanics and Automation'), ('SPECTROMETRY_SPECTROSCOPY_X-RAYS', 'Spectrometry, Spectroscopy and X-rays'), ('ELECTRONICS_TEST_ENERGY_MEASUREMENT', 'Electronics or Tests, Energy and Measurement'), ('ARTH_SCIENCES_GEOPHYSICS_ASTROPHYSICS_ARCHAEOLOGY', 'Arth Sciences, Geophysics, Astrophysics and Archaeology'), ('VACUUM_VACUUM_TECHNOLOGY_EQUIPMENT', 'Vacuum and Vacuum Technology Equipment'), ('NANOTECHNOLOGIES_MICROELECTRONICS', 'Nanotechnologies and Microelectronics'), ('NON_PURCHASING_EXPENSES', 'Non Purchasing Expenses')], max_length=100, null=True),
        ),
    ]
