# Generated by Django 5.0.3 on 2024-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0016_alter_materials_lab_supply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='lab_supply_type',
            field=models.CharField(blank=True, choices=[('COMPUTING', 'Computing'), ('ELECTRONICS', 'Electronics'), ('MECHANICAL', 'Mechanical'), ('OPTICS_LASER', 'Optics or Laser'), ('GAS_FLUIDS', 'Gas or Fluids'), ('BIOLOGICAL', 'Biological'), ('CHEMISTRY', 'Chemistry'), ('BOOKS', 'Books'), ('OFFICE_BUILDING', 'Office and Building'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
