# Generated by Django 5.0.3 on 2025-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0017_alter_materials_lab_supply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
