# Generated by Django 5.0.3 on 2025-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0018_alter_loans_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
