# Generated by Django 5.0.3 on 2025-11-25 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0019_loans_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
