# Generated by Django 5.0.3 on 2025-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0020_remove_loans_quantity_alter_loans_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
