# Generated by Django 5.0.3 on 2025-11-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0021_loans_quantity_alter_loans_loan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='lab_supply_quantity',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='lab_supply_type',
        ),
    ]
