# Generated by Django 5.0.3 on 2025-11-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0022_remove_loans_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='lab_supply_quantity',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='lab_supply_type',
            field=models.CharField(blank=True, choices=[('COMPUTING', 'Computing'), ('ELECTRONICS', 'Electronics'), ('MECHANICAL', 'Mechanical'), ('OPTICS_LASER', 'Optics or Laser'), ('GAS_FLUIDS', 'Gas or Fluids'), ('BIOLOGICAL', 'Biological'), ('CHEMISTRY', 'Chemistry'), ('BOOKS', 'Books'), ('OFFICE_BUILDING', 'Office and Building'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
