# Generated by Django 5.0.3 on 2025-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0023_materials_lab_supply_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='quantity',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
