# Generated by Django 5.0.3 on 2025-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0026_remove_loans_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
