# Generated by Django 5.0.3 on 2025-11-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0027_loans_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='quantity',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
