# Generated by Django 5.0.3 on 2025-11-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0028_alter_loans_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='quantity',
        ),
    ]
