# Generated by Django 5.0.3 on 2025-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0029_remove_loans_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='quantity_requested',
            field=models.FloatField(default=1.0),
        ),
    ]
