# Generated by Django 5.0.3 on 2025-12-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matostheque', '0030_loans_quantity_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='quantity_requested',
        ),
    ]
